[pytest]
pythonpath = backend
norecursedirs =
    .*
    build
    dist
    CVS
    _darcs
    {arch}
    *.egg
    venv
    backend/venv
    node_modules
    aquila-frontend
    backend/scripts
    scripts
    backend/data
    data
    backend/docs
    docs
